# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f8246c97a09da2c310b8c5a977f593ee224d954d78506b6d4cacd48aea6459689f4fac11532d361d85044c5f0581218a8344fe06d6e13864344e7d75ac45066

test:
  secret_key_base: 5c1892039f985d12c8e2e7b5bdf047011fd13c370dc6e27e87fa361e1b36a93444097fb8aa84d45fab724867c422cf5cda52d83987c9d2551a45b0f23444497c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
